-- AlterTable
ALTER TABLE `APRENDIZ` ADD COLUMN `horas_inasistidas` INTEGER NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `PROGRAMA` ADD COLUMN `AR` TEXT NULL,
    ADD COLUMN `modalidad` TEXT NULL,
    MODIFY `nombre` VARCHAR(100) NOT NULL;
