-- AlterTable
ALTER TABLE `PREGUNTAS` ADD COLUMN `generadaIA` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `perfilesRIASEC` VARCHAR(50) NULL;

-- AlterTable
ALTER TABLE `PROGRAMA` ADD COLUMN `perfilRIASEC` VARCHAR(10) NULL;

-- AlterTable
ALTER TABLE `REPORTE` ADD COLUMN `puntajeA` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `puntajeC` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `puntajeE` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `puntajeI` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `puntajeR` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `puntajeS` INTEGER NOT NULL DEFAULT 0,
    MODIFY `Fecha` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
