-- AlterTable
ALTER TABLE `RESPUESTAS_ASPIRANTE` ADD COLUMN `texto` TEXT NULL,
    MODIFY `valor` INTEGER NULL;

-- CreateTable
CREATE TABLE `APRENDIZ` (
    `idAPRENDIZ` INTEGER NOT NULL,
    `tipoDocumento` VARCHAR(50) NOT NULL,
    `nombre` VARCHAR(100) NOT NULL,
    `apellidos` VARCHAR(100) NOT NULL,
    `estado` BOOLEAN NOT NULL DEFAULT true,
    `programaId` INTEGER NOT NULL,

    PRIMARY KEY (`idAPRENDIZ`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `APRENDIZ` ADD CONSTRAINT `APRENDIZ_programaId_fkey` FOREIGN KEY (`programaId`) REFERENCES `PROGRAMA`(`idPROGRAMA`) ON DELETE RESTRICT ON UPDATE CASCADE;
