-- CreateTable
CREATE TABLE `PREDICCION_DESERCION` (
    `idPREDICCION` INTEGER NOT NULL AUTO_INCREMENT,
    `probabilidad` DOUBLE NULL,
    `riesgo` VARCHAR(100) NOT NULL,
    `fecha` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `aprendizId` INTEGER NOT NULL,

    PRIMARY KEY (`idPREDICCION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PREDICCION_DESERCION` ADD CONSTRAINT `PREDICCION_DESERCION_aprendizId_fkey` FOREIGN KEY (`aprendizId`) REFERENCES `APRENDIZ`(`idAPRENDIZ`) ON DELETE RESTRICT ON UPDATE CASCADE;
